version: '3.8'
services:
  database:
    container_name: webdb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'event_mangement'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: 'database'
      PMA_PORT: 3306
    ports:
      - 4000:80
  website:
    container_name: phpwebsite
    build:
      context: .
      dockerfile: Dockerfile
    image: aminabaza/event_management
    ports:
      - 9000:80

